# Generated by Django 3.2.15 on 2025-03-16 21:29

from django.db import migrations
import wangeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=wangeditor.fields.WangRichTextField(verbose_name='简介'),
        ),
    ]
