# Generated by Django 3.2.15 on 2025-03-15 21:51

from django.db import migrations, models
import wangeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('description', models.TextField(verbose_name='摘要')),
                ('content', wangeditor.fields.WangRichTextField(verbose_name='内容')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'db_table': 'tb_article',
            },
        ),
    ]
