# Generated by Django 3.2.15 on 2025-03-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AlterModelTable(
            name='video',
            table='tb_video',
        ),
    ]
