# Generated by Django 3.2.15 on 2025-03-16 21:29

from django.db import migrations
import wangeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20250317_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=wangeditor.fields.WangRichTextField(blank=True, verbose_name='摘要'),
        ),
    ]
